// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDyfl4o77Z8t3jGUA2YQUR6WCaCzYM2CA',
    appId: '1:437405270222:web:5fd1809d1ffd0b83dc109f',
    messagingSenderId: '437405270222',
    projectId: 'chatapp-cbffe',
    authDomain: 'chatapp-cbffe.firebaseapp.com',
    storageBucket: 'chatapp-cbffe.firebasestorage.app',
    measurementId: 'G-3T66EVRPQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADaRz9ijq7Z9sMxoEVgxrGwyF9pOPicLI',
    appId: '1:437405270222:android:7b7a2418748faf16dc109f',
    messagingSenderId: '437405270222',
    projectId: 'chatapp-cbffe',
    storageBucket: 'chatapp-cbffe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXcG6CywZ1g6wKxqcRTyIIv3Z1s_aHzeI',
    appId: '1:437405270222:ios:912799c14c710807dc109f',
    messagingSenderId: '437405270222',
    projectId: 'chatapp-cbffe',
    storageBucket: 'chatapp-cbffe.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXcG6CywZ1g6wKxqcRTyIIv3Z1s_aHzeI',
    appId: '1:437405270222:ios:912799c14c710807dc109f',
    messagingSenderId: '437405270222',
    projectId: 'chatapp-cbffe',
    storageBucket: 'chatapp-cbffe.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDyfl4o77Z8t3jGUA2YQUR6WCaCzYM2CA',
    appId: '1:437405270222:web:75998c23c4104c6adc109f',
    messagingSenderId: '437405270222',
    projectId: 'chatapp-cbffe',
    authDomain: 'chatapp-cbffe.firebaseapp.com',
    storageBucket: 'chatapp-cbffe.firebasestorage.app',
    measurementId: 'G-LE1Q7SJY3N',
  );
}
